### ISSUE TITLE
How to install cdm_to_delta module?

### ISSUE THREAD

**Issue by legendgod** [sergioschena/cdm-to-delta#1]
I am sorry for my newbie question. I am testing the code on databricks. When I run "from cdm_to_delta.model import" it returns
ModuleNotFoundError: No module named 'cdm_to_delta'

How should I install this module?

**Comment by sergioschena** [comment]
No problem, all the questions are more than welcome (I recognize that I could enhance the README on how to run the code in Databricks and the setup that is needed).

Can you please tell me how you have imported the code in Databricks (using Repos ?) and the runtime version you are running on ?

**Comment by legendgod** [comment]
> No problem, all the questions are more than welcome (I recognize that I could enhance the README on how to run the code in Databricks and the setup that is needed).
> 
> Can you please tell me how you have imported the code in Databricks (using Repos ?) and the runtime version you are running on ?

I think it is the problem.. I do not know how to import the code. I don't have much experience in python project.

**Comment by sergioschena** [comment]
You should leverage the [Git integration for Databricks](https://learn.microsoft.com/en-us/azure/databricks/repos/), by [cloning directly this repo](https://learn.microsoft.com/en-us/azure/databricks/repos/git-operations-with-repos#clone-a-repo-connected-to-a-remote-git-repository) into your Workspace folder.
